# Generated by Django 4.1 on 2024-09-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricityData',
        ),
    ]
