# Generated by Django 4.1 on 2024-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_electricitydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
