# Generated by Django 4.1 on 2024-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_fuelconsumption_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='has_submitted_monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='has_submitted_yearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='submitted_months',
            field=models.JSONField(default=dict),
        ),
    ]
