# Generated by Django 4.1 on 2024-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fuelconsumption_has_submitted_monthly_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuelconsumption',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='consumption_quantity',
            field=models.FloatField(),
        ),
    ]
