# Generated by Django 4.1 on 2024-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_fuelconsumption_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='consumption_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
