# Generated by Django 4.1 on 2024-09-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fuelconsumption_fuel_data_yearly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='consumption_unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='fuel_type',
            field=models.CharField(max_length=20),
        ),
    ]
