# Generated by Django 4.1 on 2024-09-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_fuelconsumption_consumption_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userelectricitysubmission',
            name='co2e_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
