# Generated by Django 4.1 on 2024-09-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userelectricitysubmission_co2e_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='total_co2e_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
