# Generated by Django 4.1 on 2024-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fuelconsumption_total_co2e_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endoflifeproduct',
            name='disposal_method',
            field=models.CharField(max_length=50),
        ),
    ]
