# Generated by Django 4.1 on 2024-10-12 11:28

import accounts.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_endoflifeproduct_disposal_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=10)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('co2e_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_monthly_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=10)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('co2e_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_yearly_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Kerosene', 'Kerosene'), ('Butane', 'Butane'), ('Propane', 'Propane'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('Coal', 'Coal')], max_length=25)),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=10)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('liter', 'liter'), ('Kg', 'Kg')], max_length=20)),
                ('co2e_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_monthly_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Kerosene', 'Kerosene'), ('Butane', 'Butane'), ('Propane', 'Propane'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('Coal', 'Coal')], max_length=25)),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=10)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('liter', 'liter'), ('Kg', 'Kg')], max_length=20)),
                ('co2e_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_yearly_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FuelYearlyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.fuel_yearly_upload)),
                ('fuel_yearly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.fuelyearly')),
            ],
        ),
        migrations.CreateModel(
            name='FuelMonthlyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.fuel_monthly_upload)),
                ('fuel_monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.fuelmonthly')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyYearlyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.energy_yearly_upload)),
                ('energy_yearly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.energyyearly')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyMonthlyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=accounts.models.energy_monthly_upload)),
                ('energy_monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.energymonthly')),
            ],
        ),
    ]
