# Generated by Django 4.1 on 2024-10-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_fuelmonthly_unit_alter_fuelyearly_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnergyMonthlyFiles',
            new_name='EnergyMonthlyFile',
        ),
        migrations.RenameModel(
            old_name='EnergyYearlyFiles',
            new_name='EnergyYearlyFile',
        ),
        migrations.RenameModel(
            old_name='FuelMonthlyFiles',
            new_name='FuelMonthlyFile',
        ),
        migrations.RenameModel(
            old_name='FuelYearlyFiles',
            new_name='FuelYearlyFile',
        ),
    ]
