# Generated by Django 4.1 on 2024-10-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_energymonthlyfiles_energymonthlyfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelmonthly',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('liter', 'liter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelyearly',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('liter', 'liter')], max_length=20),
        ),
    ]
