# Generated by Django 4.1 on 2024-10-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_fuelmonthly_unit_alter_fuelyearly_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energymonthly',
            options={'verbose_name': 'Energy Monthly Consumption'},
        ),
        migrations.AlterModelOptions(
            name='energymonthlyfile',
            options={'verbose_name': 'Energy Monthly File'},
        ),
        migrations.AlterModelOptions(
            name='energyyearly',
            options={'verbose_name': 'Energy Yearly Consumption'},
        ),
        migrations.AlterModelOptions(
            name='energyyearlyfile',
            options={'verbose_name': 'Energy Yearly File'},
        ),
        migrations.AlterModelOptions(
            name='fuelmonthly',
            options={'verbose_name': 'Fuel Monthly Consumption'},
        ),
        migrations.AlterModelOptions(
            name='fuelmonthlyfile',
            options={'verbose_name': 'Fuel Monthly File'},
        ),
        migrations.AlterModelOptions(
            name='fuelyearly',
            options={'verbose_name': 'Fuel Yearly Consumption'},
        ),
        migrations.AlterModelOptions(
            name='fuelyearlyfile',
            options={'verbose_name': 'Fuel Yearly File'},
        ),
        migrations.AlterField(
            model_name='fuelmonthly',
            name='unit',
            field=models.CharField(choices=[('liter', 'liter'), ('Kg', 'Kg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelyearly',
            name='unit',
            field=models.CharField(choices=[('liter', 'liter'), ('Kg', 'Kg')], max_length=20),
        ),
    ]
