# Generated by Django 4.1 on 2024-10-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_fuelmonthly_unit_alter_fuelyearly_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelmonthly',
            name='unit',
            field=models.CharField(choices=[('liter', 'liter'), ('Kg', 'Kg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelyearly',
            name='unit',
            field=models.CharField(choices=[('liter', 'liter'), ('Kg', 'Kg')], max_length=20),
        ),
    ]
