# Generated by Django 4.1 on 2024-10-15 03:50

import accounts.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_fuelmonthly_unit_alter_fuelyearly_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportYearlyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=10)),
                ('file', models.FileField(upload_to=accounts.models.transport_yearly_upload)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_yearly_files_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('Road', 'Road'), ('Rail', 'Rail'), ('Sea', 'Sea'), ('Air', 'Air')], max_length=25)),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('distance_unit', models.CharField(choices=[('Km', 'Km'), ('Mile', 'Mile')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight_unit', models.CharField(choices=[('Ton', 'Ton'), ('Kg', 'Kg')], max_length=25)),
                ('start', models.CharField(blank=True, max_length=200, null=True)),
                ('end', models.CharField(blank=True, max_length=200, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('co2e_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_yearly_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportMonthlyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=10)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('file', models.FileField(upload_to=accounts.models.transport_monthly_upload)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_monthly_files_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransportMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('Road', 'Road'), ('Rail', 'Rail'), ('Sea', 'Sea'), ('Air', 'Air')], max_length=25)),
                ('year', models.CharField(choices=[('FY 2015-16', '2015-16'), ('FY 2016-17', '2016-17'), ('FY 2017-18', '2017-18'), ('FY 2018-19', '2018-19'), ('FY 2019-20', '2019-20'), ('FY 2020-21', '2020-21'), ('FY 2021-22', '2021-22'), ('FY 2022-23', '2022-23'), ('FY 2023-24', '2023-24'), ('FY 2024-25', '2024-25')], max_length=10)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('distance_unit', models.CharField(choices=[('Km', 'Km'), ('Mile', 'Mile')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight_unit', models.CharField(choices=[('Ton', 'Ton'), ('Kg', 'Kg')], max_length=25)),
                ('start', models.CharField(blank=True, max_length=200, null=True)),
                ('end', models.CharField(blank=True, max_length=200, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('co2e_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_monthly_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
