# Generated by Django 4.1 on 2024-10-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_transportyearlyfiles_transportyearly_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energymonthly',
            options={'verbose_name': 'Energy Monthly'},
        ),
        migrations.AlterModelOptions(
            name='energyyearly',
            options={'verbose_name': 'Energy Yearly'},
        ),
        migrations.AlterModelOptions(
            name='fuelmonthly',
            options={'verbose_name': 'Fuel Monthly'},
        ),
        migrations.AlterModelOptions(
            name='fuelyearly',
            options={'verbose_name': 'Fuel Yearly'},
        ),
        migrations.AlterModelOptions(
            name='transportmonthly',
            options={'verbose_name': 'Transport Monthly'},
        ),
        migrations.AlterModelOptions(
            name='transportmonthlyfiles',
            options={'verbose_name': 'Transport Monthly File'},
        ),
        migrations.AlterModelOptions(
            name='transportyearly',
            options={'verbose_name': 'Tranport Yearly'},
        ),
        migrations.AlterModelOptions(
            name='transportyearlyfiles',
            options={'verbose_name': 'Transport Yearly File'},
        ),
        migrations.AlterField(
            model_name='energymonthly',
            name='month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=10),
        ),
        migrations.AlterField(
            model_name='energymonthly',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='energyyearly',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fuelmonthly',
            name='month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fuelmonthly',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('liter', 'liter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelmonthly',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fuelyearly',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('liter', 'liter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelyearly',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='months',
            name='month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transportmonthly',
            name='month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transportmonthly',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transportmonthlyfiles',
            name='month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transportmonthlyfiles',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transportyearly',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transportyearlyfiles',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=10),
        ),
        migrations.AlterField(
            model_name='years',
            name='year',
            field=models.CharField(choices=[('FY2015', 'FY2015'), ('FY2016', 'FY2016'), ('FY2017', 'FY2017'), ('FY2018', 'FY2018'), ('FY2019', 'FY2019'), ('FY2020', 'FY2020'), ('FY2021', 'FY2021'), ('FY2022', 'FY2022'), ('FY2023', 'FY2023'), ('FY2024', 'FY2024')], max_length=50),
        ),
    ]
