# Generated by Django 4.1 on 2024-10-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_energymonthly_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelmonthly',
            name='unit',
            field=models.CharField(choices=[('liter', 'liter'), ('Kg', 'Kg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelyearly',
            name='unit',
            field=models.CharField(choices=[('liter', 'liter'), ('Kg', 'Kg')], max_length=20),
        ),
    ]
